app/Http/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the controller to call when that URI is requested.
  |
 */
$middleware = [];
if(Config::get('app.debug'))
{
	array_push($middleware, ['middleware' => 'clearcache']);
}

Route::get('/', function () {
    return view('welcome');
});

Route::auth();
Route::get('/login', function () {
    return view('welcome');
});
Route::group(['middleware' => ['auth','clearcache']], function() {
Route::get('/home', 'HomeController@index');
//Route::resource('users','UserController');
Route::get('users',['as'=>'users.index','uses'=>'UserController@index','middleware' => ['permission:users-list']]);
Route::post('listingusersadmin',['uses'=>'UserController@listingusers','middleware' => ['permission:users-list']]);
Route::get('users/create',['as'=>'users.create','uses'=>'UserController@create','middleware' => ['permission:users-create']]);
Route::post('users/create',['as'=>'users.store','uses'=>'UserController@store','middleware' => ['permission:users-create']]);
Route::post('userscreate',['uses'=>'UserController@store','middleware' => ['permission:users-create']]);
Route::get('users/{id}',['as'=>'users.show','uses'=>'UserController@show']);
Route::get('users/{id}/edit',['as'=>'users.edit','uses'=>'UserController@edit','middleware' => ['permission:users-edit']]);
Route::post('usersedit',['as'=>'users.edit','uses'=>'UserController@edit','middleware' => ['permission:users-edit']]);
Route::delete('users/{id}',['as'=>'users.destroy','uses'=>'UserController@destroy','middleware' => ['permission:users-delete']]);

Route::patch('users/{id}',['as'=>'users.update','uses'=>'UserController@update','middleware' => ['permission:users-edit']]);
	
Route::patch('usersupdate',['uses'=>'UserController@update','middleware' => ['permission:users-edit']]);
	

Route::get('stores', 'UserController@storess');
Route::post('type', 'UserController@getroles');
Route::post('createuser', 'UserController@createusers');
Route::post('createuserstore', 'StoreController@createuserstore');
Route::get('addstore', ['uses'=>'StoreController@createstore','middleware' => ['permission:add-stores']]  );
Route::get('findstore', ['uses'=>'StoreController@findstore','middleware' => ['permission:find-stores']] );
Route::get('autocomplete', 'StoreController@autocomplete');
Route::get('autocompletes', 'StoreController@autocompletes');
Route::resource('liststore', 'StoreController@liststore');

Route::post('deleteuser', 'StoreController@deleteusers' );
Route::post('liststoreusers', 'StoreController@liststoreusers' );
Route::post('storedetails', 'StoreController@storedetails' );
Route::post('changepass', ['uses'=>'UserController@changepass','middleware' => ['permission:change-password']]);
Route::post('getuserdetails', 'StoreController@getuserdetails' );
Route::post('edituser', 'StoreController@edituser' );
Route::post('adddept', 'StoreController@adddept' );
Route::post('adddepts', 'StoreController@adddepts' );
Route::post('listdepartments', 'StoreController@listdepartments' );
Route::post('departmentedit', 'StoreController@departmentedit' );
Route::post('dptsupdate', 'StoreController@dptsupdate' );
Route::post('editdept',  'StoreController@editdept');
Route::post('storecreate', 'StoreController@create' );
Route::post('storeedit', 'StoreController@storeedit' );
Route::get('editstore', ['uses'=>'StoreController@editstore','middleware' => ['permission:edit-stores']]  );
Route::post('selectstore', 'StoreController@selectstores' );
Route::post('updatesprofile', ['uses'=>'RoleController@updates','middleware' => ['permission:profile-view']] );
Route::post('addstore/create', ['as'=>'store.create','uses'=>'StoreController@create'] );

    Route::post('listingroles',['uses'=>'RoleController@listingroles','middleware' => ['permission:role-list']]);
	Route::get('roles',['as'=>'roles.index','uses'=>'RoleController@index','middleware' => ['permission:role-list|role-create|role-edit|role-delete']]);
	Route::get('roles/create',['as'=>'roles.create','uses'=>'RoleController@create','middleware' => ['permission:role-create']]);
	Route::post('roles/create',['as'=>'roles.store','uses'=>'RoleController@store','middleware' => ['permission:role-create']]);	
	Route::post('rolescreate',['uses'=>'RoleController@store','middleware' => ['permission:role-create']]);
	Route::get('roles/{id}',['as'=>'roles.show','uses'=>'RoleController@show']);
	Route::get('roles/{id}/edit',['as'=>'roles.edit','uses'=>'RoleController@edit','middleware' => ['permission:role-edit']]);
	Route::post('rolesedit',['as'=>'roles.edit','uses'=>'RoleController@edit','middleware' => ['permission:role-edit']]);
	Route::patch('roles/{id}',['as'=>'roles.update','uses'=>'RoleController@update','middleware' => ['permission:role-edit']]);
	
	Route::delete('roles/{id}',['as'=>'roles.destroy','uses'=>'RoleController@destroy','middleware' => ['permission:role-delete']]);

	Route::get('itemCRUD2',['as'=>'itemCRUD2.index','uses'=>'ItemCRUD2Controller@index','middleware' => ['permission:item-list|item-create|item-edit|item-delete']]);
	Route::get('itemCRUD2/create',['as'=>'itemCRUD2.create','uses'=>'ItemCRUD2Controller@create','middleware' => ['permission:item-create']]);
	Route::post('itemCRUD2/create',['as'=>'itemCRUD2.store','uses'=>'ItemCRUD2Controller@store','middleware' => ['permission:item-create']]);
	Route::get('itemCRUD2/{id}',['as'=>'itemCRUD2.show','uses'=>'ItemCRUD2Controller@show']);
	Route::get('itemCRUD2/{id}/edit',['as'=>'itemCRUD2.edit','uses'=>'ItemCRUD2Controller@edit','middleware' => ['permission:item-edit']]);
	Route::patch('itemCRUD2/{id}',['as'=>'itemCRUD2.update','uses'=>'ItemCRUD2Controller@update','middleware' => ['permission:item-edit']]);
	Route::delete('itemCRUD2/{id}',['as'=>'itemCRUD2.destroy','uses'=>'ItemCRUD2Controller@destroy','middleware' => ['permission:item-delete']]);
	Route::get('profile/{id}',['uses'=>'UserController@showprofile','middleware' => ['permission:profile-view']]);
//storeusers
Route::get('storeprofile',['uses'=>'Stores@index','middleware' => ['permission:store-profile']] );
Route::post('liststoreuser',  ['uses'=>'Stores@liststoreuser','middleware' => ['permission:storeuser-list']]);
Route::post('editstoredata',['uses'=> 'Stores@editstoredata','middleware' => ['permission:editstore-details']]);
Route::post('addcategory', ['uses'=> 'Categorys@addcategory','middleware' => ['permission:add-category']]);
Route::post('liststoresuser', 'Stores@liststoresuser');
Route::get('storelistss', ['uses'=> 'Stores@storelists','middleware' => ['permission:store-profile']]);
Route::get('categorys',  ['uses'=> 'Categorys@index' ,'middleware' => ['permission:add-category']]);
Route::get('categorylist',  ['uses'=> 'Categorys@categorylist' ,'middleware' => ['permission:list-category']]);
Route::post('editcategory',  ['uses'=> 'Categorys@editcategory' ,'middleware' => ['permission:edit-category']]);
Route::post('editscategorylist', 'Categorys@editscategorylist');
Route::post('deletecategory', ['uses'=> 'Categorys@deletecategory' ,'middleware' => ['permission:delete-category']]);
Route::get('addproduct',  ['uses'=> 'Products@index' ,'middleware' => ['permission:add-product']]);
Route::get('listproduct', ['uses'=> 'Products@listproduct' ,'middleware' => ['permission:list-product']]);
Route::post('saveproduct', ['uses'=> 'Products@saveproduct' ,'middleware' => ['permission:add-product']]);
Route::post('updateproduct', ['uses'=> 'Products@updateproduct' ,'middleware' => ['permission:edit-product']]);
Route::post('removepic', 'Products@removepic');
Route::post('editproduct', ['uses'=> 'Products@editproduct' ,'middleware' => ['permission:edit-product']]);
Route::post('deleteproduct', ['uses'=> 'Products@deleteproduct','middleware' => ['permission:delete-product']]);
Route::post('selectcategory', 'Categorys@selectcategory');
Route::post('getdepatments', 'Products@getdepatments');
Route::post('listingproducts', 'Products@listingproducts');
Route::get('import',['uses'=>'Products@import','middleware' => ['permission:import']]);
Route::post('dumpproduct', ['uses'=>'Products@dumpproduct','middleware' => ['permission:import']]);
Route::post('changedpt', 'Categorys@changedpt');
Route::post('deletestore', 'Stores@deletestore');
Route::post('deletedpartmt','Stores@deletedpartmt');

Route::post('roleupdate', ['uses'=>'RoleController@roleupdate','middleware' => ['permission:role-edit']]);
Route::post('deleterole', ['uses'=>'RoleController@destroy','middleware' =>['permission:role-delete']]);
Route::post('deleteduser', ['uses'=>'UserController@destroy','middleware' =>['permission:users-delete']]);
Route::post('listingcategory', ['uses'=>'Categorys@listingcategory','middleware' =>['permission:list-category']]);
Route::get('downloadExcel/{type}', 'Products@downloadExcel');
//Route::resource('store', 'stores');
//sooraj
Route::post('changepassed', ['uses' => 'Stores@changepass', 'middleware' => ['permission:storechange-password']]);
Route::post('storeprofiles', ['as' => 'store.update', 'uses' => 'Stores@updates']);
Route::post('state', 'StoreController@state');
Route::post('city', 'StoreController@city');
Route::post('createcity','StoreController@insertcity');
Route::get('listOrders', ['uses' => 'OrdersController@listOrders']);
Route::get('listcustomer','OrdersController@listCustomer');
Route::post('getOrders','OrdersController@getOrders');
Route::post('getnewOrderss','OrdersController@getnewOrders');
Route::post('getfulfilmentOrderss','OrdersController@getfulfilmentOrders');
Route::post('getassignedOrderss','OrdersController@getassignedOrders');
Route::post('getcompletedOrderss','OrdersController@getcompletedOrders');

app/Http/Controllers/Stores.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use App\Http\Controllers\Controller;
use App\User;
use App\Role;
use App\Store;
use App\Departments;
use DB;
use Session;
use Image;
use Hash;

class Stores extends Controller {

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function index() {
        $id = Session::get('id');

        $user = User::find($id);
        return view('storeuser.storeprofile', compact('user'));
    }

    public function storelists() {
        $id = Session::get('id');
        $user = User::find($id);
        $dept = DB::table('departments')->where('store_id', '=', $user->store_id)->where('type', '=', '0')->get();
        $roles = DB::table('roles')->where('type', '=', '1')->get();
        $users = DB::table('users')->orderBy('id', 'desc')->first();
		$countries = DB::table('countries')->get();
        return view('storeuser.list', ['countries' => $countries,'roles' => $roles, 'users' => $users, 'dept' => $dept]);
    }

    public function liststoreuser(Request $request) {
        $id = Session::get('id');
        $user = User::find($id);
       // $users = Store::find($user->store_id);
        $list = DB::table('users')
                ->join('role_user', 'users.id', '=', 'role_user.user_id')
                ->join('roles', 'roles.id', '=', 'role_user.role_id')
                ->select('users.*', 'roles.display_name', 'roles.id as role_id ')
                ->where('users.store_id', $user->store_id)
                ->get();
		$users = Store::leftJoin('countries','stores.country','=','countries.id')
             ->leftJoin('states','stores.state','=','states.id')
             ->leftJoin('cities','stores.city','=','cities.id')
             ->select('stores.*')
             ->where('stores.id', '=',$user->store_id)
             ->get();		
        print_r(json_encode(array('users' => $users[0], 'storeuser' => $list)));
    }

    public function liststoresuser(Request $request) {
        $id = $request->id;
        $user = User::where("store_id", $id);
        //$users = Store::find($user->store_id);
        print_r(json_encode($user));
    }

    public function editstoredata(Request $request) {
		
        $input = $request->all();
       $id =$input['id'];
	   
	   $res = Store::where("mail",$input['mail'])->where('id','!=', $id)->get();
        if(count($res)==0){
       if(isset($input['mcity']))
       {
        $cityinsert=array(["name"=>$input['mcity'],"state_id"=>$input['state']]);
        
        $id2=DB::table('cities')->insert($cityinsert);
        $store_id = DB::table('cities')->orderBy('id', 'desc')->first();
        $input['city']=$store_id->id;
//        $last = Timelog::orderBy('id', 'desc')->first();
        
       
       }
	   if (Input::file()) {

            $image = Input::file('image');
            $filename = time() . '.' . $image->getClientOriginalExtension();
            $name = Input::file('image')->getClientOriginalName();
            $extension = $image->getClientOriginalExtension();
            // RENAME THE UPLOAD WITH RANDOM NUMBER 
            $fileName = rand(11111, 99999) . '.' . $extension;
            $path = public_path('logo');
            $thumb_img = Image::make($image->getRealPath())->resize(200, 140);
            $thumb_img->save($path.'/'.$fileName,80);
            //$image->move($path, $fileName);
            $input['image'] = 'logo/' . $fileName;
        }
		if($input['image'] ){
			$input['image']=$input['image'];
		}else{
			 $row =Store::where("id", $id)->get();
			 $input['image']=$row[0]->logo;
		}
        $id = $input['id'];
		$item = array(
                
                "name" => $input['name'],
                "corporateidentifier" => $input['corporateidentifier'],
                "address" => $input['address'],
                "address2" => $input['address2'],
                "city" => $input['city'],
                "state" => $input['state'],
                "country" => $input['country'],
                "zip" => $input['zip'],
                "phone" => $input['phone'],
                "mail" => $input['mail'],
                "website" => $input['website'],
				"latitude" => $input['latitude'],
                "longitude" => $input['longitude'],
				"opening_time" => $input['opening_time'],
                "closing_time" => $input['closing_time'],
				   "logo"=>$input['image']
        );
        Store::where("id", $id)->update($item);
        $row =Store::where("id", $id)->get();
        //$item = Item::find($id);
        print_r(json_encode(array('status' => 'success','class' => 'alert alert-success', 'msg' => 'Store Updated Succesfully','logo'=>$row[0]->logo)));
		}else{
			print_r(json_encode(array('status' => 'failed','class' => 'alert alert-warning', 'msg' => 'Email ID Exist')));
		
		}
    }

    public function changepass(Request $request) {

        $input = $request->all();
        $id = $input['id'];
        $ress = User::find($id);
        $input['password'] = Hash::make($input['changepass']);

        if (count($ress) == 1) {

            //if (Hash::check($request->input('currentpass'), $ress->password)) {
                $user = User::find($id);

                $user->update($input);
                print_r(json_encode(array('status' => 'success', 'msg' => 'Password Changed Succesfully')));
            //} else {
              //  print_r(json_encode(array('status' => 'failed', 'msg' => 'Current Password is incorrect ')));
            //}
        }
    }

    public function updates(Request $request) {

        $id = $request->input('id');
        $name = $request->input('name');
        $firstname = $request->input('firstname');
        $lastname = $request->input('lastname');
        $type = $request->input('type');
        $email = $request->input('email');
        $contactnumber = $request->input('contactnumber');
		 $res = User::where("email",$email)->where('id', '!=',  $id)->get();
		
        if(count($res)==0){
			DB::update('update users set name = ?,firstname = ? ,lastname =? ,type = ?, email = ?, contactnumber = ? where id = ?', [$name, $firstname, $lastname, $type, $email, $contactnumber, $id]);
            print_r(json_encode(array('status' => 'success', 'class' => 'alert alert-success','msg' => 'Profile Updated Succesfully')));
		}else{
			print_r(json_encode(array('status' => 'failed', 'class' => 'alert alert-danger','msg' => 'Email ID Exist')));
		}

       

        //return redirect()->back();
        
        //return redirect()->back()->with('message','Operation Successful !');
    }
	public function deletestore(Request $request) {
		$input = $request->all();
        $ids = $input['id'];
		
		$product =DB::table('productinventories')->where('store_id', '=', $ids)->delete();
		
		$categories =DB::table('categories')->where('store_id', '=', $ids)->delete();
		$departments =DB::table('departments')->where('store_id', '=', $ids)->delete();
		$user =DB::table('users')->where('store_id', '=', $ids)->delete();
		
		
		
		    
		Store::destroy($ids);
		print_r(json_encode(array('status' => 'success', 'msg' => "Store Deleted Succesfully")));	
		
		 
	}
	public function getresults($table,$id) {
		
		$result = DB::table($table)->where('store_id', '=', $id);
		
		 return $result;
	}
	public function deletedpartmt(Request $request) {
		$input = $request->all();
        $id = $input['id'];
		$product =DB::table('productinventories')->where('department_id', '=', $id)->delete();
		$categories =DB::table('categories')->where('departments_id', '=', $id)->delete();
		$departments =DB::table('departments')->where('id', '=', $id)->delete();
		print_r(json_encode(array('status' => 'success', 'msg' => "Departments Deleted Succesfully")));
	}

}

resources/views/store/create.blade.php
@extends('layouts.app')

@section('content')



<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Create User</h2>
        <ol class="breadcrumb">
            <li>
                <a ui-sref="orders.new_orders">Home</a>
            </li>
            <li class="">
                <a href="{{ url('/users') }}"> Users</a>
            </li>
            <li class="active">
                Create User 
            </li>
        </ol>
    </div>

</div>
<div class="row">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5> Store User </h5>    
        </div>
        <div class="ibox-content">

            @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif

            {!! Form::open(array('route' => 'users.store','class'=>'form-horizontal','method'=>'POST')) !!}
            <div class="form-group"><label class="col-lg-2 control-label">Name</label>

                <div class="col-lg-8">   {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!} <span
                        class="help-block m-b-none"></span>
                </div>
            </div> 
            <div class="form-group"><label class="col-lg-2 control-label">Firstname</label>

                <div class="col-lg-8">   {!! Form::text('firstname', null, array('placeholder' => 'firstname','class' => 'form-control')) !!} <span
                        class="help-block m-b-none"></span>
                </div>
            </div>
            <div class="form-group"><label class="col-lg-2 control-label">Lastname</label>

                <div class="col-lg-8">   {!! Form::text('lastname', null, array('placeholder' => 'lastname','class' => 'form-control')) !!} <span
                        class="help-block m-b-none"></span>
                </div>
            </div>

            <div class="form-group"><label class="col-lg-2 control-label">Contactnumber</label>

                <div class="col-lg-8">   {!! Form::text('contactnumber', null, array('placeholder' => 'contactnumber','class' => 'form-control')) !!} <span
                        class="help-block m-b-none"></span>
                </div>
            </div>
            <div class="form-group"><label class="col-lg-2 control-label">Email</label>

                <div class="col-lg-8">   {!! Form::text('email', null, array('placeholder' => 'email','class' => 'form-control')) !!} <span
                        class="help-block m-b-none"></span>
                </div>
            </div>
            <div class="form-group"><label class="col-lg-2 control-label">Password</label>

                <div class="col-lg-8">   {!! Form::password('password', null, array('placeholder' => 'password','class' => 'form-control')) !!} <span
                        class="help-block m-b-none"></span>
                </div>
            </div>
            <div class="form-group"><label class="col-lg-2 control-label">Confirm Password</label>

                <div class="col-lg-8">   {!! Form::password('confirm-password', null, array('placeholder' => 'Confirm Password','class' => 'form-control')) !!} <span
                        class="help-block m-b-none"></span>
                </div>
            </div>
            <div class="form-group"><label class="col-lg-2 control-label">Type</label>

                <div class="col-lg-8">  <select class="form-control m-b " name="type" ><option ></option>
                        <option value="0" >User</option>
                        <option value="1" >Store</option>
                    </select> <span
                        class="help-block m-b-none"></span>
                </div>
            </div>

            <div class="form-group"><label class="col-lg-2 control-label">Role</label>

                <div class="col-lg-8">
                    <input type="hidden" value="1" name="store_id">
                    {!! Form::select('roles[]', $roles,[], array('class' => 'form-control','multiple')) !!}</div>
            </div>


            <div class="form-group">
                <div class="col-lg-offset-2 col-lg-8">
                    <button type="btn btn-md btn-primary" class="btn btn-primary" >Submit</button>

                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>
</div>


@endsection

resources/views/store/edit.blade.php
@extends('layouts.app')

@section('content')



<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Edit User</h2>
        <ol class="breadcrumb">
            <li>
                <a ui-sref="orders.new_orders">Home</a>
            </li>
            <li class="">
                <a href="{{ url('/users') }}"> Users</a>
            </li>
            <li class="active">
                Edit New User
            </li>
        </ol>
    </div>

</div>
<div class="row">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Edit users</h5>    
        </div>
        <div class="ibox-content">
            @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            {!! Form::model($user, ['method' => 'PATCH','class'=>'form-horizontal','route' => ['users.update', $user->id]]) !!}

            <div class="form-group"><label class="col-lg-2 control-label">Name</label>

                <div class="col-lg-8">    {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!} <span
                        class="help-block m-b-none"></span>
                </div>
            </div>
            <div class="form-group"><label class="col-lg-2 control-label">Firstname</label>

                <div class="col-lg-8">   {!! Form::text('firstname', null, array('placeholder' => 'firstname','class' => 'form-control')) !!} <span
                        class="help-block m-b-none"></span>
                </div>
            </div>
            <div class="form-group"><label class="col-lg-2 control-label">Lastname</label>

                <div class="col-lg-8">   {!! Form::text('lastname', null, array('placeholder' => 'lastname','class' => 'form-control')) !!} <span
                        class="help-block m-b-none"></span>
                </div>
            </div>

            <div class="form-group"><label class="col-lg-2 control-label">Contactnumber</label>

                <div class="col-lg-8">   {!! Form::text('contactnumber', null, array('placeholder' => 'contactnumber','class' => 'form-control')) !!} <span
                        class="help-block m-b-none"></span>
                </div>
            </div>
            <div class="form-group"><label class="col-lg-2 control-label">Type</label>

                <div class="col-lg-8">  <select class="form-control m-b " name="type" ><option <?php if ($user->type == '') echo"selected"; ?>></option>
                        <option value="0"  <?php if ($user->type == '0') echo"selected"; ?>>User</option>
                        <option value="1" <?php if ($user->type == '1') echo"selected"; ?>>Store</option>
                    </select> <span
                        class="help-block m-b-none"></span>
                </div>
            </div>
            <div class="form-group"><label class="col-lg-2 control-label">Email</label>

                <div class="col-lg-8">{!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}
                </div>
            </div>
            <div class="form-group"><label class="col-lg-2 control-label" >Password</label>

                <div class="col-lg-8">
                    <label>  {!! Form::password('password', array('placeholder' => 'Password','class' => 'form-control')) !!}</label>

                </div>
            </div> <div class="form-group"><label class="col-lg-2 control-label" >Confirm Password</label>

                <div class="col-lg-8">
                    <label>  {!! Form::password('confirm-password', array('placeholder' => 'Confirm Password','class' => 'form-control')) !!}</label>

                </div>
            </div><div class="form-group"><label class="col-lg-2 control-label" >Role</label>

                <div class="col-lg-8">
                    <label> {!! Form::select('roles[]', $roles,$userRole, array('class' => 'form-control','multiple')) !!}</label>

                </div>
            </div>

            <div class="form-group">
                <div class="col-lg-offset-2 col-lg-8">
                    <button type="btn btn-md btn-primary" class="btn btn-primary">Submit</button>

                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>
</div>


@endsection

resources/views/store/show.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Show User</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('users.index') }}"> Back</a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Name:</strong>
            {{ $user->name }}
        </div>
    </div><div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Firstname:</strong>
            {{ $user->firstname }}
        </div>
    </div><div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Lastname:</strong>
            {{ $user->lastname }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Contact Number:</strong>
            {{ $user->contactnumber }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Email:</strong>
            {{ $user->email }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Roles:</strong>
            @if(!empty($user->roles))
            @foreach($user->roles as $v)
            <label class="label label-success">{{ $v->display_name }}</label>
            @endforeach
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/store/store.blade.php
@extends('layouts.app')

@section('content')




<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Users</h2>
        <ol class="breadcrumb">
            <li>
                <a ui-sref="orders.new_orders">Home</a>
            </li>

            <li class="active">
                <strong>Stores</strong>
            </li>
        </ol>
    </div>
    <div class="col-sm-8">

    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5> Stores </h5>            
            </div>		
            <div class="ibox-content">
                <a href="{{ route('users.create') }}" class="btn btn-primary">Add users</a>
                <table class="table table-bordered topspace">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th> Name </th>

                            <th>Address</th>
                            <th>city</th>


                            <th class="">Action</th>



                        </tr>
                    </thead>
                    <tbody>
                        <?php $i = 0;
                        ?>@foreach ($roles as $key => $user)
                        <tr>
                            <td>{{ ++$i }}</td>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->address }}</td>
                            <td>{{ $user->city }}</td>

                            <td>
                                <a class="btn btn-info" href="{{ route('store.show',$user->id) }}">Show</a>
                                <a class="btn btn-primary" href="{{ route('store.edit',$user->id) }}">Edit</a>
                                {!! Form::open(['method' => 'DELETE','route' => ['store.destroy', $user->id],'style'=>'display:inline']) !!}
                                {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                                {!! Form::close() !!}
                            </td>
                        </tr>
                        @endforeach


                    </tbody>
                </table>


            </div>
        </div>

    </div>
</div>





@endsection